### ISSUE TITLE
Fix: Delete should not be zero based index

### ISSUE THREAD

**Issue by larrylawl** [se-edu/duke#11]
Specification of `delete` in [website](https://nus-cs2103-ay1920s1.github.io/website/schedule/week2/project.html) is zero-indexed.
![Screenshot 2019-08-18 at 2 10 32 PM](https://user-images.githubusercontent.com/40198156/63220862-7a3ac980-c1c2-11e9-8cdf-2b87b2e6be0f.png)

This is inconsistent with `done` and `list`
![Screenshot 2019-08-18 at 2 10 49 PM](https://user-images.githubusercontent.com/40198156/63220867-bcfca180-c1c2-11e9-8ba1-3699c69bc1e2.png)

**Comment by damithc** [comment]
Good catch @larrylawl 
Fixed.
