### ISSUE TITLE
JavaFxTutorial 3: Missing assets

### ISSUE THREAD

**Issue by alyip98** [se-edu/duke#6]
![image](https://user-images.githubusercontent.com/2277141/63069537-d21acb80-bf49-11e9-8807-f74d48721dd4.png)

These assets are only available on the `ui-with-gradle` branch, which is what the app should look like after JavaFxTutorial 4. They should be made available on the master branch or another resources branch?

**Comment by damithc** [comment]
@j-lum Let's make them available in the tutorial page (with instructions) i.e., students should download the images from the tutorial page and save in the correct location.

@alyip98 were you able to get the images to show up?

**Comment by alyip98** [comment]
It crashed on start without the images. I noticed they were missing and switched to the `ui-with-gradle` branch.

**Comment by damithc** [comment]
> It crashed on start without the images. I noticed they were missing and switched to the `ui-with-gradle` branch.

There shouldn't be such a branch in https://github.com/nus-cs2103-AY1920S1/duke 
You must be using se-edu/duke instead

**Comment by j-lum** [comment]
Actually they are supposed to get two images themselves but we could provide it if needed.
