### ISSUE TITLE
Possibly replace check and cross marks with simple characters

### ISSUE THREAD

**Issue by okkhoy** [se-edu/duke#64]
Many students can't get the tick and cross marks to work either in the IDE or in the terminal or both.
They end up spending time on getting that right.
Instead, we could replace those with simple characters `Y`es and `N`o for the status.
See https://github.com/nus-cs2113-AY2021S1/forum/issues/31 for a context.

**Comment by damithc** [comment]
Yes, we should do that next time.

**Comment by damithc** [comment]
Done
